name: indiekit
services:
  indiekit:
    build: .
    restart: always
    ports:
      - ${HTTP_PORT:-3000}:3000
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_URL=mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@mongo
      - PASSWORD_SECRET
      - SECRET
      - PUBLICATION_URL
      - GITHUB_TOKEN
      - GITHUB_USER
      - GITHUB_REPO
      - GITHUB_BRANCH
      - TZ
  mongo:
    image: mongo:4.4.17
    ports:
        - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_URL=mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@mongo
volumes:
  mongo-data:
    external: true
